[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cat-dog-classifier-service"
version = "0.1.0"
# Notice that 'packages' is no longer here.

[tool.setuptools]
# This is the correct place for tool-specific instructions.
packages = ["app"]